#!/usr/bin/zsh
if [[ "$1" == "-a" ]]
then
	export DISPLAY=-
	export SSH_ASKPASS=$0
	export SSH_AUTH_SOCK=/run/user/$(id -u $PAM_USER)/ssh-agent
	ssh-add ~$PAM_USER/.ssh/id_ed25519 </dev/null
else
	id=$(keyctl request user login @s) || exit 1
	keyctl pipe $id | base64
fi
